### ISSUE TITLE
Index out of bound exception when the library tries to parse base station observation data in rinex 3.03

### ISSUE THREAD

**Issue by YuanjieZhao** [rtklibexplorer/rtklib-py#2]
Hi. When I execute `run_ppk.py` on my input data in rinex 3.03 format, the library throws index out of bound exception when it tries to parse base station observation data in rinex 3.03, even though the same input files can be parsed correctly RTKLIB or other tools.

### Exception message
```
Traceback (most recent call last):
  File ".../src/run_ppk.py", line 82, in <module>
    base.decode_obsfile(nav, basefile, None)
  File ".../src/rinex.py", line 321, in decode_obsfile
    self.decode_obs(nav, maxepoch)
  File .../src/rinex.py", line 292, in decode_obs
    obs.L[n, f] = float(obs_)
IndexError: index 2 is out of bounds for axis 1 with size 2
```

### How to reproduce
The exception can be reproduced with the input files below (attached in a zip file) 
[receiver and base data.zip](https://github.com/rtklibexplorer/rtklib-py/files/8719461/receiver.and.base.data.zip)

- `rectangle_walk.22o` is the rover observatoin data
- `DRAO00CAN_R_20220160000_01D_MN.rnx` is the base station navigation data
- `DRAO00CAN_R_20220160000_01D_30S_MO.rnx` is the base station observation data
- The config file is the same as [config_f9p.py](https://github.com/rtklibexplorer/rtklib-py/blob/main/src/config_f9p.py) because this file matches my settings in rtklib.

All observatoin data and navigation data are in rinex 3.03 format

The base station data is pulled from [Canadian Active Control System (CACS)](https://webapp.csrs-scrs.nrcan-rncan.gc.ca/geod/data-donnees/cacs-scca.php?locale=en). These are public base stations managed by government. I use base station close to British Columbia, Canada.

### My investigation so far
When the library is parsing the body of base station observation data, it loops through`range(self.nsig[sys])` using the following code
```
                for i in range(self.nsig[sys]):
....
                    f = i // (self.nsig[sys] // self.nband[sys])
                    if self.typeid[sys][i] == 0:  # code
                        obs.P[n, f] = float(obs_)
....
```

The index out of bound exception is thrown when 
```
i = 13
self.nsig[sys] = 20
self.nband[sys] = 6
f = 2
```

`obs.P` only has 2 columns, so f =2 triggers index out of bound exception

I didn't figure out why this line compute `f` in this way
```
f = i // (self.nsig[sys] // self.nband[sys])
```
https://github.com/rtklibexplorer/rtklib-py/blob/main/src/rinex.py#L284

**Comment by rtklibexplorer** [comment]
Currently rtklib-py can not parse complex observation files with many extra signals not used in the solution.  I have just submitted a change to improve error handling and report a more relevant error.  To run your example you will need to first simplify the base observation file by doing a rinex->rinex translation with RTKCONV and use the mask button in the "Options" menu to filter out the unused signals. 

On a separate note, you will want to use the config_phone.py configuration file, not the config_f9p.py file since you are trying to do a L1/L5 solution, not a L1/L2 solution.
