### ISSUE TITLE
Generate RINEX from UBX

### ISSUE THREAD

**Issue by lucapada** [rtklibexplorer/rtklib-py#3]
Hi, I have a question regarding this library. I have developed a program in Python that establishes a connection with an EVK-M8T ublox receiver, sends configuration messages to receive RAWX and SFRBX type messages, and then collects the received stream of bytes into a .ubx file (removing NMEA sentences and putting only UBX messages). I would like to be able to generate RINEX files from this file that I generate by collecting the bytes that arrive using the library. is it possible to do this? I have some questions about this, in case it is possible:
- Is the UBX file that contains the stream okay like this?
- is it possible to generate the .XXo RINEX observations file (where XX is the year of observation) and get several RINEX files for the navigations, one per constellation (for example: .XXn for GPS, .XXg for GLONASS, .XXe for Galileo)?
- Is it possibile to choose the RINEX version (3.01 or 3.05)?

If this library is not for me, how could I do it?
I apologize in advance for the triviality of my question, but I really have very little experience in this area. Thank you very much in advance.

**Comment by rtklibexplorer** [comment]
This can be done with RTKLIB but not with rtklib-py.
