### ISSUE TITLE
Velocity output 

### ISSUE THREAD

**Issue by MrBourriz** [rtklibexplorer/rtklib-py#7]
How to get the velocity in the output file ?

**Comment by etfredeluces** [comment]
Please correct me if I am wrong, but I think velocity estimation is not included. The supposed values for velocity in pntpos.py sol.rr[3:6] is 0. But I think this can be done by following rtklib code

**Comment by rtklibexplorer** [comment]
Correct, rtklib-py does not have an option to output velocity to the solution file, although the estimated velocities are in nav.x[3:6], so adding this feature would be relatively simple.  RTKLIB does have an option to output velocity to the solution file.
